#!/usr/bin/env python

import asyncio
import websockets

async def echo(websocket, path):
    message = await websocket.recv()
    print(message)

    await websocket.send("recieved")

asyncio.get_event_loop().run_until_complete(
    websockets.serve(echo, '0.0.0.0', 8765))
asyncio.get_event_loop().run_forever()
